### ISSUE TITLE
Incompatibility of plugin with Flutter 3.7.0-13.0.pre.79 leads to build failure

### ISSUE THREAD

**Issue by nfnfgo** [idootop/custom_nested_scroll_view#6]
I'm using Flutter master branch, and I just pulled the lastest update and try starting my app, however I got an error from this plugin file.

My Flutter and Dart version info is below:

```
Flutter 3.7.0-13.0.pre.79 • channel master • https://github.com/flutter/flutter.git
Framework • revision 91c3f80c8c (15 hours ago) • 2022-12-27 04:44:24 -0500
Engine • revision 790604a09f
Tools • Dart 3.0.0 (build 3.0.0-64.0.dev) • DevTools 2.20.0
```

And in this version of Flutter, after I tried to start my app, I got this error (I tried flutter clean and pub get however the problem still there):
```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
lib\main.dart:1
: Error: The method '_NestedScrollMetrics.copyWith' doesn't have the named parameter 'devicePixelRatio' of overridden method 'Object with ScrollMetrics.copyWith'.
../…/src/nested_scroll_view.dart:526
  _NestedScrollMetrics copyWith({
                       ^
/C:/flutter/packages/flutter/lib/src/widgets/scroll_metrics.dart:43:17: Context: This is the overridden method ('copyWith').
  ScrollMetrics copyWith({
                ^

: Error: The superclass, 'FixedScrollMetrics', has no unnamed constructor that takes no arguments.
../…/src/nested_scroll_view.dart:514
  _NestedScrollMetrics({
  ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1157

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by idootop** [comment]
Just upgrade your Flutter to the new master version. 
```bash
flutter upgrade
```
<img width="593" alt="图片" src="https://user-images.githubusercontent.com/35302658/209748356-0ea0dde0-9a51-4e69-9ff3-e26588f97951.png">

Because someone broke it 5 days ago and reverted it 5 hours ago. :(

<img width="1265" alt="图片" src="https://user-images.githubusercontent.com/35302658/209748885-b758d8d5-110c-4a7a-8ad2-13f48aef0c75.png">

You can check it here: [Flutter Commit: 999356b776f70132d569a37f13f65333a1bb0779](https://github.com/flutter/flutter/commit/999356b776f70132d569a37f13f65333a1bb0779#diff-fa4c7cc0eb7b3bc4dddafd251e5070421a68cec8ea89d9c7ff2ce244653af4d2)

**Comment by nfnfgo** [comment]
It works! Thanks for answering!

**Comment by nfnfgo** [comment]
Sorry to disturb, but seems they had relanded that commit 😭 

![image](https://user-images.githubusercontent.com/61616918/213459647-7033d270-0b74-4361-9991-35eb59cc509a.png)

And after upgrade my Flutter, the completely same error info appearred again

**Comment by idootop** [comment]
-_-|||   So sad, I recommand you to use the latest stable or dev channel than the master channel.
